### ISSUE TITLE
Playtest Version 3 (STePs Build)

### ISSUE THREAD

**Issue by iskandarzulkarnaien** [Lightcaster-Studios/Beamerman#110]
**Soft deadline: Thursday, 8 April** [So we have time for poster, trailer, slides and website]
**_Hard deadline: Friday, 9 April_** [Items due for STePS]

Here are the issues I think we should include:

I have grouped the list according to the features that I are closely related (and thus prone to conflicts with each other)

Level/HUD/UI Related:
- [X] Victory Screen UI #40 (Completed by Ranice)
- [x] Victory Screen Race Conditions Bug #140
- [ ] Mayhem Mode Soft Transition #88 (Assigned to Iskandar)
- [x] Display Drone Count on HUD #116
- [x] Display Stat Levels on HUD #117
- [x] Unify Game Art #112 

Drone Related:
- [x] New PowerUp: DroneCount++ #105 (Completed by Iskandar)
- [x] Make Drones Block Player Movement #106 (Completed by Iskandar)

Player/Lazer Related:
- [x] Player Colored Lazers #68 (Completed by Iskandar)
- [X] Rework PowerUp Visuals (Completed by Dan)
- [x] Rework PowerUp PickUp Effect #125 (Assigned to Dan)
- [X] UI Scaling Issue #77 (Completed by Ranice)

No Conflicts:
- [X] Gridify BaseTile Texture #83 (Assigned to Daryl)
- [x] Game Icon for built game #109 (Assigned to Daryl)
- [X] AI Improvements #66 (Completed by Hong Wen)
- [x] AI Reflections and Damage Avoidance #131 (Assigned to Hong Wen)
- [x] Map Rework #65 (Assigned to Dan)
- [ ] Make temp powerup (armor effect) flash when nearing expiry #85 (Assigned to Dan)

Additionally, we also have several items to prepare for STePS:
- [x] Slides (Assigned to Daryl)
- [x] Poster (Assigned to Daryl)
- [x] Trailer (Assigned to Daryl)
- [ ] Website (Assigned to Ranice)
