### ISSUE TITLE
Prototype 2

### ISSUE THREAD

**Issue by iskandarzulkarnaien** [Lightcaster-Studios/Beamerman#29]
This issue description is WIP. If you want to edit it please do me the courtesy of letting me know below before editing thank you.

### Player:
- [x] Player get hit by lazer (PR #31)

### Player Movement:
- [ ] Ensure smooth player movement
- [ ] Proper Snap To Grid
- [ ] Bonk Into Mirror/Walls must properly redirect
### Lazer:
- [ ] Many Bugs and shit
- [ ] Lazer too slow?
- [x] Prism projectiles weird  (PR #31)
- [x] Lazer Charge Up Mechanic (PR #31)
- [ ] Player Colored Lazers
### Environment Objects:
- [x] Consolidate Tiles (PR #30)
- [x] Implement Glass Wall (PR #30)
- [ ] Implement Skyhook Pillar
- [x] Implement Barrier Block (PR #30)
### Powerups:
- [x] Implement Behavior (PR #41)
- [x] Bug: Lazers destroy powerups (PR #28)
- [x] Change them to not spawn every time (PR #28)
- [ ] Make them spawn randomly (stretch)
### Map:
- [ ] Basic Beamerman Map
### Sound:
- [x] Sounds for everything (PR #43)
- [X] Music for game (PR #39)
- [x] Make Music Loop (PR #43)
### Graphics:
- [X] Env objects v ugly (PR #37)
### Misc:
- [ ] Time Limit
- [ ] Mayhem Mode
### AI:
- [ ] Basic motions

### UI:
- [ ] UI Elements for displaying health and other stats
